# Generated by Django 3.0.6 on 2020-05-08 04:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_remove_student_college'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2020, 5, 8))),
                ('end_date', models.DateField(default=datetime.date(2020, 5, 8))),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 8, 4, 23, 38, 432745, tzinfo=utc))),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.College')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
