# Generated by Django 3.0.6 on 2020-05-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
    ]
